alias s := send
alias b := build

send:
    rsync -avz -e "ssh -i ~/gipop_plc" /Users/ander/Documents/proj/palanuk/anc/runtime/target/aarch64-unknown-linux-gnu/release/palanuk-runtime pi@raspberrypi.local:/home/pi/palanuk/anc

build:
    cargo zigbuild --target aarch64-unknown-linux-gnu --release
